name: EventCore
version: ${version}
api-version: 1.21
main: me.david.EventCore
author: VertrauterDavid, JavaMio
load: POSTWORLD
website: https://github.com/DavidArchive/EventCore
canvas-supported: true
softdepend: [PlaceholderAPI]
depend: [WorldEdit]